# Generated by Django 5.0.1 on 2024-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionattemptmodel',
            name='question_with_answer',
        ),
        migrations.AddField(
            model_name='userquestionattemptmodel',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
