# Generated by Django 5.0.1 on 2024-10-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresultmodel',
            name='passed',
        ),
    ]
