# Generated by Django 5.0.1 on 2024-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresultmodel',
            name='correct_answers',
        ),
        migrations.AddField(
            model_name='quizresultmodel',
            name='answers',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
