# Generated by Django 4.2.7 on 2023-11-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sourceInfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubtopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics_of_topic', to='questions_app.topicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=150)),
                ('answers', models.JSONField(default=list)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='questions_app.subtopicmodel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='questions_app.topicmodel')),
            ],
        ),
    ]
