# Generated by Django 4.2.7 on 2023-11-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='sourceInfo',
            new_name='source',
        ),
    ]
