# Generated by Django 4.2.7 on 2023-11-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0002_rename_sourceinfo_topicmodel_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='source',
            field=models.URLField(),
        ),
    ]
