# Generated by Django 5.0.1 on 2024-10-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0002_userquestionattemptmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
