# Generated by Django 5.0.1 on 2024-10-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0003_alter_topicmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='description',
            field=models.TextField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
