# Generated by Django 4.2.7 on 2023-11-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0003_alter_topicmodel_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicmodel',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='questions_app.topicmodel'),
        ),
    ]
