# Generated by Django 4.2.7 on 2023-11-13 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0004_alter_subtopicmodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicmodel',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='questions_app.topicmodel'),
            preserve_default=False,
        ),
    ]
