# Generated by Django 5.0.1 on 2024-10-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0004_rename_name_topicmodel_title_topicmodel_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuestionAttemptModel',
        ),
    ]
