# Generated by Django 4.2.7 on 2023-11-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0005_alter_subtopicmodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question',
            field=models.TextField(max_length=300),
        ),
    ]
