# Generated by Django 4.2.7 on 2023-11-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0007_alter_questionmodel_subtopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='source',
        ),
    ]
