# Generated by Django 5.0.1 on 2024-01-05 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('topic', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions_app.topicmodel')),
            ],
        ),
    ]
