# Generated by Django 4.2.7 on 2023-11-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0006_alter_questionmodel_question'),
        ('pdf_files_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions_app.topicmodel'),
        ),
    ]
