# Generated by Django 4.2.7 on 2023-11-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0007_alter_questionmodel_subtopic_and_more'),
        ('pdf_files_app', '0005_alter_pdffile_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions_app.topicmodel'),
        ),
    ]
