# Generated by Django 4.2.7 on 2023-11-22 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0008_remove_topicmodel_source'),
        ('pdf_files_app', '0006_alter_pdffile_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions_app.topicmodel'),
        ),
    ]
