# Generated by Django 5.0.1 on 2024-10-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizzes_app.quizcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_app.questionmodel')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes_app.quizmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', related_query_name='quiz', through='quizzes_app.QuizQuestionModel', to='questions_app.questionmodel'),
        ),
        migrations.AddConstraint(
            model_name='quizquestionmodel',
            constraint=models.UniqueConstraint(fields=('quiz', 'question'), name='unique_quiz_question'),
        ),
        migrations.AddConstraint(
            model_name='quizmodel',
            constraint=models.UniqueConstraint(fields=('number', 'category'), name='unique_number_category'),
        ),
    ]
