# Generated by Django 5.0.1 on 2024-09-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_app.questionmodel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes_app.quizmodel')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test', 'question')},
            },
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='quizzes_app.QuizQuestion', to='questions_app.questionmodel'),
        ),
    ]
