# Generated by Django 5.0.1 on 2024-09-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0001_initial'),
        ('quizzes_app', '0004_alter_quizmodel_questions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestionmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', related_query_name='quiz', through='quizzes_app.QuizQuestionModel', to='questions_app.questionmodel'),
        ),
        migrations.AddConstraint(
            model_name='quizquestionmodel',
            constraint=models.UniqueConstraint(fields=('quiz', 'question'), name='unique_quiz_question'),
        ),
    ]
