# Generated by Django 5.0.1 on 2024-10-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_app', '0004_rename_name_topicmodel_title_topicmodel_description'),
        ('quizzes_app', '0007_quizcategorymodel_quizmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='quizmodel',
            constraint=models.UniqueConstraint(fields=('number', 'category'), name='unique_number_category'),
        ),
    ]
