# Generated by Django 5.0.1 on 2024-10-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0008_quizmodel_number_quizmodel_unique_number_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResultModel',
        ),
    ]
