# Generated by Django 5.0.1 on 2024-12-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicMetricsModel',
        ),
    ]
